name: Docker
on:
  push:
    tags:
      - '*'
  schedule:
    # monthly on day 5
    - cron: '5 5 5 * *'
  workflow_dispatch:

permissions:
  artifact-metadata: write
  attestations: write
  id-token: write
  packages: write

jobs:
  ndn-python-repo:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: ndn-python-repo
