name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12', 'pypy-3.10']

    services:
      nfd:
        image: ghcr.io/named-data/nfd:latest
        volumes:
        - /run/nfd:/run/nfd

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # - name: Setup node for the following actions
      #   run: |
      #     apt-get update && apt-get install -y software-properties-common npm
      #     npm install npm@latest -g && npm install n -g && n latest
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip3 install ".[dev]"
      - name: Setup PIB and TPM
        run: |
          pyndnsec Init-Pib
          pyndnsec New-Item /test
      - name: Run tests
        run: pytest tests
