name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        python-version: ['3.7', '3.8', '3.9']

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev python3-setuptools
          git clone https://github.com/named-data/ndn-cxx.git && cd ndn-cxx
          git checkout ndn-cxx-0.7.0
          sudo ./waf configure && sudo ./waf && sudo ./waf install && cd ..
          git clone https://github.com/named-data/NFD.git && cd NFD
          git checkout NFD-0.7.0
          sudo ./waf configure --without-libpcap --without-websocket && sudo ./waf && sudo ./waf install && cd ..
          sudo ldconfig
          ndnsec-key-gen test
          sudo nfd start -c /usr/local/etc/ndn/nfd.conf.sample &
          pip3 install pytest
          pip3 install wheel
          pip3 install .

      - name: Run tests
        run: pytest