name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12', 'pypy-3.10']

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev python3-setuptools
          git clone --depth=1 --recursive --branch ndn-cxx-0.8.1 https://github.com/named-data/ndn-cxx.git
          cd ndn-cxx
          sudo ./waf configure && sudo ./waf && sudo ./waf install && cd ..
          git clone --depth=1 --recursive --branch NFD-22.12 https://github.com/named-data/NFD.git && cd NFD
          sudo ./waf configure --without-libpcap --without-websocket && sudo ./waf && sudo ./waf install && cd ..
          sudo ldconfig
          ndnsec-key-gen test
          sudo nfd start -c /usr/local/etc/ndn/nfd.conf.sample &
          pip3 install ".[dev]"
      - name: Run tests
        run: pytest tests
